DB_CONNECT: user=postgres password=password host=localhost port=5439 dbname=banner_test sslmode=disable
cancel: 15
userToken: userToken
adminToken: adminToken
port: 8080
redisConn: redis://localhost:6379